### ISSUE TITLE
Admin: extend API to include pipelines

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway#386] opened 2017-08-29 16:30 UTC

**Comment by DrMegavolt** [comment] 2017-09-13 08:41
Assuming  it will add new pipeline with 'name' and either will contain no policies or will include some dummy policy if YAWN is not fixed

**Comment by DrMegavolt** [comment] 2017-09-29 08:19
this task is  to define API endpoints for granular Pipelines API 
https://docs.google.com/document/d/1qgeYckdTuoQE24wZrju40jef92nTeNO0nIQXyfsCA38/edit?ts=59cdf8d8#

@altsang Please define at what level we need to stop in this spec

**Comment by XVincentX** [comment] 2018-01-03 11:58
@DrMegavolt Can we close this? We have such API now.

**Comment by DrMegavolt** [comment] 2018-01-03 12:25
closing as duplicate of #418. Already implemented

**Closed by DrMegavolt** 2018-01-03 12:25 UTC
