### ISSUE TITLE
Replace Webdriver+phantomjs with puppeteer

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway#516] opened 2017-11-07 15:43 UTC
Webdriver + phantomjs is an exaggerate solution for the type of testing we want to do. Puppetteer might be probably a better idea.

We need to test a behaviour and not make sure it works on crossbrowser scenarios.

**Comment by DrMegavolt** [comment] 2017-12-05 11:37
I think you've tried it in #531 and it didn't work. too unstable project. 
closing for now. e2e tests for oauth2 are working just fine

**Closed by DrMegavolt** 2017-12-05 11:37 UTC
Labels: enhancement

**Comment by XVincentX** [comment] 2017-12-05 11:44
> I think you've tried it in #531 and it didn't work. too unstable
…which is why there's an open issue, or not?

If you want to close this ok, but if we close it it's going to be difficult to keep track of it and we'll forget about it.

**Comment by DrMegavolt** [comment] 2017-12-05 11:46
it is not a bug, and it is using standard tools. so I'm not sure if it is a tech debt  
I any case it is super low priority.

**Comment by XVincentX** [comment] 2017-12-05 11:58
> I'm not sure if it is a tech debt

Points of view. I think it is because PhantomJS has been declared as deprecated and his creator said "switch to puppeteer".

> In any case it is super low priority.

Absolutely, we can live with it (probably for 10 years), but there might be people looking at the issues and contributing to it. Having closed means "We're not going to fix this". I mean, having this open shouldn't really harm anyone.

Anyway — we're going into the philosophy of the open issues 😄 — I'm fine in keeping it closed. I'll set up a personal remark in 6 months 😏
