### ISSUE TITLE
How to get user detail in proxy api

### ISSUE THREAD

**Issue by aroopghoshtarento** [ExpressGateway/express-gateway#933] opened 2019-07-24 07:33 UTC
Hi,

I am using oauth2 policy and i need to get the logged in user detail in my proxy endpoint, but i am could not able to get that. I tried using forwardHeaders, but in that i get consumers but not the users.

**Comment by XVincentX** [comment] 2019-07-24 08:39
@aroopghoshtarento Can you show how you're creating the user and how you're sending such header?

**Comment by aroopghoshtarento** [comment] 2019-07-24 08:54
I created the user from eg users create
then i created the app and credentials for oauth and basic-auth

**Comment by aroopghoshtarento** [comment] 2019-07-24 08:57
policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - oauth2:
         - action:
            passThrough: true
      - headers:
         - action:
              headersPrefix: 'eg-'
              forwardHeaders:
                id: 'consumer.id'
                consumer-name: 'consumer.name'
                consumer-type: 'consumer.type'
                requestID: 'requestID'
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

**Comment by XVincentX** [comment] 2019-07-27 08:15
@aroopghoshtarento I'm assuming you're using the opaque token and not the JWT, is that correct?

**Comment by XVincentX** [comment] 2019-07-27 08:21
By the way this is a duplicate of #888 — let's keep the conversation there.

**Closed by XVincentX** 2019-07-27 08:21 UTC
