### ISSUE TITLE
[bugs] CLI: eg credentials list -c <userId>

### ISSUE THREAD

**Issue by ahwing210** [ExpressGateway/express-gateway#361] opened 2017-08-02 07:19 UTC
Hi EG Team,

I follow the [getting started guide](http://www.express-gateway.io/getting-started/) and try some other CLI commands.
The CLI command "**eg credentials list**" can show the user credentials with "**User username**".
However, it seems that the CLI command "**eg credentials list**" cannot show the user credentials with "**User Id**". 

Please find below screenshot for trying..

1. eg credentials list -c 795872c9-6c01-410c-9dcd-395b353befd9
**# not successful**
2. eg credentials list -c bob
**# successful**

![image](https://user-images.githubusercontent.com/15073442/28861032-9e3e9352-7791-11e7-9e7c-b9e953548a2e.png)

**Comment by DrMegavolt** [comment] 2017-08-02 15:16
@ahwing210 Thank you for finding issue. 
Indeed new credential for user  will be linked to whatever is provided as consumer: user id or username. and this should not be that way. 

if used as `eg users create -c username ....` then 'eg credentials list -c username' will work  
if used as `eg users create -c userid ....` then 'eg credentials list -c userid' will work 

while quick way to fix exists,  it maybe not that simple to fix root cause, can take some time 

for now in key-auth scenario  please use userId

**Comment by DrMegavolt** [comment] 2017-08-29 15:20
Is related to https://docs.google.com/document/d/15s3njiBfbfiwvwPuylcYfJlG4fvm_QJDJ54IKakyUiI/edit#heading=h.igsojut9cpcj

**Comment by altsang** [comment] 2017-10-24 17:03
@XVincentX - please assume new - please write up spec first

**Comment by XVincentX** [comment] 2017-10-25 15:43
Guys — I've been looking at the code and here are my considerations:

Both `username` and `id` are unique for an `user`. This means that one implies the other and viceversa. That's redundant.

If this affirmations holds with the passing of the time - and I think it will - I personally do not see any reason to have this duplicate value. 

I'd rather promote `username` as the `id` of the object and simply remove the `uuid` generated by the gateway, so the only way to look for an user would be by `id` - that is the username.

Regardless I'm right on the uniqueness of the things or not, I would prefer that the gateway itself (and the exposed webapi) would only deal with the `id`. All these byproducts (such as get by username, filtering things and so on and so forth) should be implemented in the CLI - in the same way we did with #428 : [filtering](https://github.com/ExpressGateway/express-gateway/blob/master/bin/generators/credentials/list.js#L3) is happening on the CLI.

What's your idea?

**Comment by DrMegavolt** [comment] 2017-10-25 15:57
I like the idea of referencing every related record by id. having it as sometimes id sometimes username gives all those problems. 

I believe id should be uuid = automatically always unique, no logic required. 
and username is alias to id. it is not a primary key

I like your idea to have some alias endpoint 
`GET /users/alias/username -> guid 200`
`GET /users/alias/guid -> guid (same guid as requested) 200` 
`GET /users/alias/something-not-existing -> 404`
same for app 

so CLI will do call to the alias API, 
will get for sure existing uuid 
proceed with original operation or fail even before trying, because user does not exist

**Comment by DrMegavolt** [comment] 2017-10-25 16:04
there is already similar implicit logic for similar use case (verification of username-> userid -> appid resolving )
 https://github.com/ExpressGateway/express-gateway/blob/master/lib/rest/routes/credentials.js#L96

if API will always accept id, this can be simplified to avoid username check

**Comment by kevinswiber** [comment] 2017-10-25 17:06
Having a user ID separate from the username is a common pattern.  Here's the reasoning: 1) referential integrity is always preserved with the user ID and 2) there's flexibility in changing the user-facing username.

We allow user interactions to take advantage of the friendlier username because this is easier for humans to remember.

This is a question of where we put the complexity of determining whether we're dealing with a user ID or a username.  The complexity doesn't go away; it just shifts around.

If we put it behind the API, the complexity is kept on the server.  If we put it in the CLI, the complexity is kept on the client.

My preference is to leave this complexity on the server, as it prevents the burden of duplicating this logic across current and future clients.  What are the concerns with this approach?

**Comment by DrMegavolt** [comment] 2017-10-25 19:20
@kevinswiber  I don't have preference. Just trying to make API usage simpler (as well as implementation).
Let say in context of some UI you already know the user, so in this case you would just use UserId
so no call to `alias` endpoint is needed at all 

This removes this logic from both server and client

The only client that may not be aware of UserId is CLI, so this seems to be the only place to contain complicated logic

**Comment by XVincentX** [comment] 2017-10-25 19:27
@kevinswiber 
> There's flexibility in changing the user-facing username.

Good point, I didn't think about it at first glance. I also checked Kong and they do the same.
Let's keep both.

> My preference is to leave this complexity on the server, as it prevents the burden of duplicating this logic across current and future clients. What are the concerns with this approach?

I agree that if we keep the things on the server all the clients will receive the things for free, but on the other hand 

1. I'd like to avoid the API to blown up with a lot of endpoints in order to:

- Search by userId
- Search by username
- Search by date
- Search by _that custom field nobody cares_
...and so on and so forth.

2. If we implement the WebApi for that in the core, we can't go back or change it unless we break it. Instead, if we roll on the thing on the CLI first, we can "escalate" it and extract it as an SDK javascript library if people really want it (and the CLI could use it as well), and eventually incorporate the API in the gateway itself using exactly the same library.
I've been looking at Stripe as a reference and they do not provide any search capability (nor does Kong)

3. Another possibility that I see is that — our plugin system will hopefully improve over the time, so if you *REALLY* want such method you can extend the Admin API and do that on your own.

Does that make sense?

**Comment by altsang** [comment] 2017-10-26 01:53
Agreed. The whole reason why this came up was to avoid a user, support person or admin to have to remember some obscure GUUID to do everyday manipulations. 

I was thinking to either search by username as default and then by userid or that we search by explicit flag and not to do two searches if nothing specified. Both should be unique.

**Closed** 2017-10-31 16:47 UTC
Labels: bug, in progress
